def main():
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")
    print("Good morning, World!")

if __name__ == '__main__':
    main()